import { popluateDayHours } from "../helpers/populateDayHours";
import { IFlight, IFlightBoard } from "../types/data";
import { nanoid } from "@reduxjs/toolkit";
import { dayConverter } from "../helpers/dayConverter";

export const today = dayConverter(new Date(), 0);
export const tomorrow = dayConverter(new Date(), 1);
export const yesterday = dayConverter(new Date(), -1);

export const selectDates = [yesterday, today, tomorrow];

export const selectTimes = popluateDayHours();

export const terminals = ["ALL", "A", "B", "C", "D", "E", "F"];

export const flightsList: IFlight[] = [
  {
    id: nanoid(),
    date: today,
    city: "Москва",
    direction: "arrival",
    time: 9,
    flight_number: "TW 213",
    company: "Аэрофлот",
    flight_status: "CANCELLED",
    gate: "C 242",
    terminal: "A",
  },
  {
    id: nanoid(),
    date: today,
    city: "Джакарта",
    direction: "arrival",
    time: 10,
    flight_number: "BN 52",
    company: "Marine Air",
    flight_status: "ARRIVED",
    gate: "C 242",
    terminal: "A",
  },
  {
    id: nanoid(),
    date: today,
    city: "Берлин",
    direction: "arrival",
    time: 9,
    flight_number: "PP 024",
    company: "RT 5",
    flight_status: "CANCELLED",
    gate: "C 242",
    terminal: "A",
  },
  {
    id: nanoid(),
    date: yesterday,
    city: "Казань",
    direction: "arrival",
    time: 5,
    flight_number: "TW 213",
    company: "Аэрофлот",
    flight_status: "ARRIVED",
    gate: "C 242",
    terminal: "A",
  },
  {
    id: nanoid(),
    date: tomorrow,
    city: "Волгоград",
    direction: "arrival",
    time: 7,
    flight_number: "TW 213",
    company: "Аэрофлот",
    flight_status: "FLYING",
    gate: "C 242",
    terminal: "A",
  },
  {
    id: nanoid(),
    date: yesterday,
    city: "Самара",
    direction: "arrival",
    time: 3,
    flight_number: "TW 213",
    company: "Аэрофлот",
    flight_status: "ARRIVED",
    gate: "RS 229",
    terminal: "C",
  },
  {
    id: nanoid(),
    date: today,
    city: "Абу-Даби",
    direction: "arrival",
    time: 17,
    flight_number: "TW 213",
    company: "S7",
    flight_status: "FLYING",
    gate: "C 242",
    terminal: "A",
  },
  {
    id: nanoid(),
    date: tomorrow,
    city: "Казань",
    direction: "arrival",
    time: 6,
    flight_number: "TW 213",
    company: "Аэрофлот",
    flight_status: "CANCELLED",
    gate: "X 242",
    terminal: "B",
  },
  {
    id: nanoid(),
    date: yesterday,
    city: "Москва",
    direction: "arrival",
    time: 1,
    flight_number: "TW 213",
    company: "S7",
    flight_status: "CANCELLED",
    gate: "C 242",
    terminal: "C",
  },
  {
    id: nanoid(),
    date: today,
    city: "Нью-Йорк",
    direction: "departure",
    time: 5,
    flight_number: "TW 213",
    company: "Аэрофлот",
    flight_status: "CANCELLED",
    gate: "C 242",
    terminal: "A",
  },
  {
    id: nanoid(),
    date: yesterday,
    city: "Пекин",
    direction: "departure",
    time: 20,
    flight_number: "TS 213",
    company: "Аэрофлот",
    flight_status: "ARRIVED",
    gate: "C 242",
    terminal: "D",
  },
  {
    id: nanoid(),
    date: today,
    city: "Казань",
    direction: "departure",
    time: 5,
    flight_number: "TSW 333",
    company: "S7",
    flight_status: "CANCELLED",
    gate: "C 242",
    terminal: "A",
  },
  {
    id: nanoid(),
    date: today,
    city: "Нью-Йорк",
    direction: "departure",
    time: 5,
    flight_number: "WS 555",
    company: "Аэрофлот",
    flight_status: "CANCELLED",
    gate: "C 242",
    terminal: "A",
  },
  {
    id: nanoid(),
    date: today,
    city: "Каир",
    direction: "departure",
    time: 14,
    flight_number: "МВ 813",
    company: "S7",
    flight_status: "ARRIVED",
    gate: "C 242",
    terminal: "F",
  },
  {
    id: nanoid(),
    date: tomorrow,
    city: "Лондон",
    direction: "departure",
    time: 12,
    flight_number: "VX 100",
    company: "S7",
    flight_status: "CANCELLED",
    gate: "А 242",
    terminal: "A",
  },
];

export const flightBoard: IFlightBoard = {
  flights: flightsList,
  suggested_flights: [],
  board_type: "departure",
  filters: {
    query: "",
    selected_date: today,
    selected_time_range: "",
    selected_terminal: "ALL",
  },
};
